version: '3'
services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: konjikun
      POSTGRES_PASSWORD: board_konjikun
      POSTGRES_DB: postgresql
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local
